### ISSUE TITLE
features requests:  split direction, never save

### ISSUE THREAD

**Issue by pgnd** [SaidTorres3/separate-code#3]
this is a nicely useful extension!

(1)
a config/setting option to set the default editor split direction would be useful.
atm, when I 'Separate Code', it always splits down.
it'd be useful to set the default -- e.g. to be split-right -- and to have a contextual-menu option to select direction to override the default

(2)
the option to save SeparatedCode is a useful _option_ to have.
it's not what I'm finding my usual workflow to be ...
i typically open a file, select my focus, and SeparateCode.  make my edits -- which sync to the main/parent code -- then close the SeparateCode window.  which invokes the Save/Don'tSave dialog.
the default in settings would be useful.

**Comment by SaidTorres3** [comment]
So strange that it always splits down, I tried on different computers/monitors, and it always splits right

**Comment by SaidTorres3** [comment]
@pgnd If you want the split to be on the right, you can configure your vscode settings.json (ctrl + ,) adding this line to fix it:
```json
{
    ...
    "workbench.editor.openSideBySideDirection": "right",
    ...
}
```

**Comment by SaidTorres3** [comment]
Currently, I'm unable to find a way to bypass the Save dialog, and neither can o1-preview. If I come up with a solution, I’ll be sure to revisit this.

**Comment by pgnd** [comment]
@SaidTorres3 

> If you want the split to be on the right, you can configure your vscode settings.json (ctrl + ,) adding this line to fix it:
> 
> ```json
> {
>     ...
>     "workbench.editor.openSideBySideDirection": "right",
>     ...
> }
> ```

that, indeed causes the separate-code to split the editor to the right.
i had in my settings,
```
"workbench.editor.openSideBySideDirection": "down",
```
no idea what had set that; i never did, knowingly anyway.

so the `default` setting can be successfully changed. thx!

does a convenient option to selectively switch currently exist?
that mentioned context-menu choice, assignable to a keystroke as well, is probably the most useful to my usual workflow ...

**Comment by pgnd** [comment]
@SaidTorres3 

> Currently, I'm unable to find a way to bypass the Save dialog, and neither can o1-preview. If I come up with a solution, I’ll be sure to revisit this.

Does this help? Just stumbled on it ....

https://code.visualstudio.com/docs/editor/codebasics#_hot-exit

At first read, think it _might_.  Don't want to apply a global setting necessarily, rather 'just' for the extension.

Reading further ....

**Comment by SaidTorres3** [comment]
> @SaidTorres3
> 
> > Currently, I'm unable to find a way to bypass the Save dialog, and neither can o1-preview. If I come up with a solution, I’ll be sure to revisit this.
> 
> Does this help? Just stumbled on it ....
> 
> https://code.visualstudio.com/docs/editor/codebasics#_hot-exit
> 
> At first read, think it _might_. Don't want to apply a global setting necessarily, rather 'just' for the extension.
> 
> Reading further ....

"hot-exit" feature doesn't solve the issue is because hot-exit is designed to preserve unsaved changes globally across all files when you close or restart Visual Studio Code. It doesn't apply to individual tabs as far I know.

**Comment by SaidTorres3** [comment]
I found a way to not show the Save prompt dialog, expect a new version in a few weeks...

**Comment by SaidTorres3** [comment]
Version 3.0.0 released, go and check it out!
